name: Build docker image

# manual run or push new tags
on:
  workflow_dispatch:
  push:
    tags:
      - '1*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: aniven/odoo-env
          tags: |
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}
